# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
timezone: Asia/Hong_Kong
feed_url: http://www.road-beers.com
email: us@road-beers.com

gallerytag:
    dir: photos
    url: /photos
    thumb_width: 300
    thumb_height: 300
    columns: 4

paginate: 5
paginate_path: "/blog/page:num/"

plugins: [ 'jekyll-paginate' ]

highlighter: true
markdown: kramdown

sass:
    style: compressed